// Homepage data Fetching
export const FETCH_POPULAR_DATA = "FETCH_POPULAR_DATA";
export const FETCH_POPULAR_DATA_START = "FETCH_POPULAR_DATA_START";

export const EDITOR_PICK_START = "EDITOR_PICK_START";
export const EDITOR_PICK_SUCCESS = "EDITOR_PICK_SUCCESS";
export const EDITOR_PICK_FAIL = "EDITOR_PICK_FAIL";

export const FETCH_MAIN_START = "FETCH_MAIN_START";
export const FETCH_MAIN_SUCCESS = "FETCH_MAIN_SUCCESS";
export const FETCH_MAIN_FAIL = "FETCH_MAIN_FAIL";

export const GET_NORMAL_DATA_START = "GET_NORMAL_DATA_START";

export const POST_SUBSCRIBE = "POST_SUBSCRIBE";
export const SUBSCRIBE_FAIL = "SUBSCRIBE_FAIL";

export const FETCH_MAGAZINE_START = "FETCH_MAGAZINE_START";
export const FETCH_MAGAZINE_FAIL = "FETCH_MAGAZINE_FAIL";
export const FETCH_MAGAZINE_SUCCESS = "FETCH_MAGAZINE_SUCCESS";

export const FETCH_NORMAL_MB = "FETCH_NORMAL_MB";
export const FETCH_TRENDING = "FETCH_TRENDING";

export const SEARCH_FAIL = "SEARCH_FAIL";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_START = "SEARCH_START";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const PASSWORD_MISMATCH = "PASSWORD_MISMATCH";

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const POST_BOOKMARK = "POST_BOOKMARK";
export const POST_BOOKMARK_FAIL = "POST_BOOKMARK_FAIL";
export const GET_BOOKMARK = "GET_BOOKMARK";
export const GET_BOOKMARK_FAIL = "GET_BOOKMARK_FAIL";

export const LIKE_FAIL = "LIKE_FAIL";
export const LIKE_SUCCESS = "LIKE_SUCCESS";

export const GET_LIKE = "GET_LIKE";

export const GET_PACKAGES_START = "GET_PACKAGES_START";
export const GET_PACKAGES_SUCCESS = "GET_PACKAGES_SUCCESS";
export const GET_PACKAGES_FAIL = "GET_PACKAGES_FAIL";

// get alacarte items
export const GET_A_LA_CARTE_ITEMS = "GET_A_LA_CARTE_ITEMS";

//post subscription Data

export const POST_SUBSCRIPTION_DATA = "POST_SUBSCRIPTION_DATA";
export const POST_SUBSCRIPTION_FAIL = "POST_SUBSCRIPTION_FAIL";
export const POST_A_LA_CARTE_ITEM_SUCCESS = "POST_A_LA_CARTE_ITEM_SUCCESS";
export const POST_A_LA_CARTE_ITEM_FAIL = "POST_A_LA_CARTE_ITEM_FAIL";

// article details actions types

export const GET_ARTICLE_DETAILS_START = "GET_ARTICLE_DETAILS_START";
export const GET_ARTICLE_DETAILS_SUCCESS = "GET_ARTICLE_DETAILS_SUCCESS";
export const GET_ARTICLE_DETAILS_FAIL = "GET_ARTICLE_DETAILS_FAIL";

//comment section Actions

export const POST_COMMENT = "POST_COMMENT";
export const GET_COMMENT_START = "GET_COMMENT_START";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_FAIL = "GET_COMMENT_FAIL";

// profile data get actions

export const GET_PROFILE_START = "GET_PROFILE_START";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";
export const GET_PUBLIC_PROFILE = "GET_PUBLIC_PROFILE";
//profile edit post action

export const POST_PROFILE_SUCCESS = "POST_PROFILE_SUCCESS";

// category list action

export const CATEGORY_LIST_START = "CATEGORY_LIST_START";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

// category results get action

export const CATEGORY_LIST_RESULT_START = "CATEGORY_LIST_RESULT_START";
export const CATEGORY_LIST_RESULT__SUCCESS = "CATEGORY_LIST_RESULT__SUCCESS";
export const CATEGORY_LIST_RESULT__FAIL = "CATEGORY_LIST_RESULT__FAIL";

// related articles action

export const RELATED_ARTICLE_SUCCESS = "RELATED_ARTICLE_SUCCESS";
export const GET_TAGS_LINK = "GET_TAGS_LINK";

// follow/unfollow actions

export const POST_FOLLOW = "POST_FOLLOW";
export const POST_UNFOLLOW = "POST_UNFOLLOW";
